name: make_a_dream
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1


environment:
  sdk: '>=3.4.1 <4.0.0'

isar_version: &isar_version 3.1.0

dependencies:
  badges: ^3.1.2
  blur: ^4.0.0
  bonfire: ^3.9.3
  cupertino_icons: ^1.0.6
  date_time_format: ^2.0.1
  extended_image: ^8.2.1
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.0.0
  flutter_layout_grid: ^2.0.7
  flutter_radar_chart: ^0.2.1
  flutter_riverpod: ^2.5.1
  isar: *isar_version
  isar_flutter_libs: *isar_version # dart run build_runner build
  json_annotation: ^4.9.0 # dart run build_runner build
  langchain_lib:
    git:
      url: https://github.com/guchengxi1994/langchain_lib
  markdown_widget: ^2.3.2+6
  path_provider: ^2.1.2
  riverpod: ^2.5.1
  toastification: ^2.0.0
  

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  json_serializable: ^6.8.0
  package_rename: ^1.6.0   # dart run package_rename


dependency_overrides:
  analyzer: ^6.4.1
  
flutter:

  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/images/
    - assets/images/tiled/punnyworld/
    - assets/opening/

icon_path : &icon_path "assets/icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: *icon_path
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: *icon_path
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: *icon_path
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: *icon_path